set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(_VECTORCLICK_ZIG_TOOL_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(CMAKE_C_COMPILER "${_VECTORCLICK_ZIG_TOOL_DIR}/zig-cc")
set(CMAKE_CXX_COMPILER "${_VECTORCLICK_ZIG_TOOL_DIR}/zig-cxx")
set(CMAKE_RC_COMPILER "${_VECTORCLICK_ZIG_TOOL_DIR}/zig-rc.py")
set(CMAKE_RC_COMPILER_ID MSVC)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
